"""Thesis-stage contracts for approved editorial arguments."""

from __future__ import annotations

from pydantic import AliasChoices, Field

from augmented_investor.models.common import StrictBaseModel


class ScenarioMathDetails(StrictBaseModel):
    """Scenario math generated by the thesis stage."""

    Included: bool = Field(default=False, validation_alias=AliasChoices("Included", "included"))
    Projections: list[str] = Field(
        default_factory=list,
        validation_alias=AliasChoices("Projections", "projections"),
    )


class ThesisBrief(StrictBaseModel):
    """Structured thesis output that must be approved before drafting."""

    CentralThesis: str = Field(validation_alias=AliasChoices("CentralThesis", "centralThesis"))
    ThesisBasis: str = Field(validation_alias=AliasChoices("ThesisBasis", "thesisBasis"))
    BullCase: str = Field(validation_alias=AliasChoices("BullCase", "bullCase"))
    BaseCase: str = Field(validation_alias=AliasChoices("BaseCase", "baseCase"))
    BearCase: str = Field(validation_alias=AliasChoices("BearCase", "bearCase"))
    ScenarioMath: ScenarioMathDetails = Field(
        default_factory=ScenarioMathDetails,
        validation_alias=AliasChoices("ScenarioMath", "scenarioMath"),
    )
    WhatMispricing: str = Field(validation_alias=AliasChoices("WhatMispricing", "whatMispricing"))
    ContrarianTest: str = Field(validation_alias=AliasChoices("ContrarianTest", "contrarianTest"))
    ContrarianAnswer: str | None = Field(
        default=None,
        validation_alias=AliasChoices("ContrarianAnswer", "contrarianAnswer"),
    )
    NewsletterAngle: str = Field(
        validation_alias=AliasChoices("NewsletterAngle", "newsletterAngle"),
    )
    Confidence: str = Field(validation_alias=AliasChoices("Confidence", "confidence"))
    ConfidenceRationale: str = Field(
        validation_alias=AliasChoices("ConfidenceRationale", "confidenceRationale"),
    )


ScenarioMath = ScenarioMathDetails
