"""Thesis-stage contracts for approved editorial arguments."""

from __future__ import annotations

import json
from typing import Any

from pydantic import AliasChoices, Field, model_validator

from augmented_investor.models.common import StrictBaseModel


class ScenarioMathDetails(StrictBaseModel):
    """Scenario math generated by the thesis stage."""

    Included: bool = Field(default=False, validation_alias=AliasChoices("Included", "included"))
    Projections: list[str] = Field(
        default_factory=list,
        validation_alias=AliasChoices("Projections", "projections"),
    )


class ThesisBrief(StrictBaseModel):
    """Structured thesis output that must be approved before drafting."""

    CentralThesis: str = Field(validation_alias=AliasChoices("CentralThesis", "centralThesis"))
    ThesisBasis: str = Field(validation_alias=AliasChoices("ThesisBasis", "thesisBasis"))
    BullCase: str = Field(validation_alias=AliasChoices("BullCase", "bullCase"))
    BaseCase: str = Field(validation_alias=AliasChoices("BaseCase", "baseCase"))
    BearCase: str = Field(validation_alias=AliasChoices("BearCase", "bearCase"))
    ScenarioMath: ScenarioMathDetails = Field(
        default_factory=ScenarioMathDetails,
        validation_alias=AliasChoices("ScenarioMath", "scenarioMath"),
    )
    WhatMispricing: str = Field(validation_alias=AliasChoices("WhatMispricing", "whatMispricing"))
    ContrarianTest: str = Field(validation_alias=AliasChoices("ContrarianTest", "contrarianTest"))
    ContrarianAnswer: str | None = Field(
        default=None,
        validation_alias=AliasChoices("ContrarianAnswer", "contrarianAnswer"),
    )
    NewsletterAngle: str = Field(
        validation_alias=AliasChoices("NewsletterAngle", "newsletterAngle"),
    )
    Confidence: str = Field(validation_alias=AliasChoices("Confidence", "confidence"))
    ConfidenceRationale: str = Field(
        validation_alias=AliasChoices("ConfidenceRationale", "confidenceRationale"),
    )

    @model_validator(mode="before")
    @classmethod
    def _normalize_live_thesis_shape(cls, Value):
        """Normalize richer live LLM thesis objects into the strict contract."""

        if not isinstance(Value, dict):
            return Value
        Normalized = dict(Value)
        Normalized.pop("topic", None)
        Normalized.pop("Topic", None)
        for FieldName in ("bullCase", "BullCase", "baseCase", "BaseCase", "bearCase", "BearCase"):
            if FieldName in Normalized:
                Normalized[FieldName] = _stringify_thesis_value(Normalized[FieldName])
        for FieldName in ("confidence", "Confidence"):
            if FieldName in Normalized:
                Normalized[FieldName] = _stringify_confidence_value(Normalized[FieldName])
        for FieldName in ("scenarioMath", "ScenarioMath"):
            if FieldName in Normalized:
                Normalized[FieldName] = _normalize_scenario_math(Normalized[FieldName])
        return Normalized


ScenarioMath = ScenarioMathDetails


def _stringify_thesis_value(value: Any) -> str:
    """Convert richer case objects into readable single-string thesis cases."""

    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        PreferredParts = [
            value.get(Key)
            for Key in ("summary", "case", "description", "rationale", "thesis")
            if value.get(Key)
        ]
        if PreferredParts:
            return " ".join(str(Part) for Part in PreferredParts)
    return json.dumps(value, default=str)


def _stringify_confidence_value(value: Any) -> str:
    """Convert confidence objects into a compact confidence label."""

    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        for Key in ("level", "rating", "confidence", "score"):
            if value.get(Key):
                return str(value[Key])
    return json.dumps(value, default=str)


def _normalize_scenario_math(value: Any) -> Any:
    """Drop unsupported scenario-math keys and map scenarios to projections."""

    if not isinstance(value, dict):
        return value
    Projections = value.get("projections") or value.get("Projections") or value.get("scenarios") or []
    if isinstance(Projections, list):
        ProjectionStrings = [_stringify_thesis_value(Item) for Item in Projections]
    else:
        ProjectionStrings = [_stringify_thesis_value(Projections)]
    return {
        "included": bool(value.get("included", value.get("Included", ProjectionStrings))),
        "projections": ProjectionStrings,
    }
